name: ci

on:
  workflow_dispatch

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORYNAME }}:${{ github.sha }} 
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  

  docker_run:
    runs-on: self-hosted
    needs: docker_push
    steps:
    - name: Remove previous version
      timeout-minutes: 120
      run: |
        docker stop text_to_picture_bot
        docker rm text_to_picture_bot
    - name: Docker start
      timeout-minutes: 180
      run: |
        docker run -d \
        -e API_KEY=${{ secrets.API_KEY }} \
        -e TOKEN=${{ secrets.TOKEN }} \
        -e MONGO=${{ secrets.MONGO }} \
        --name text_to_picture_bot \
        ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORYNAME }}:${{ github.sha }}