name: some

on:   
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: github.event.repository.name
    steps:
      - run: |
            echo $REPO_NAME
