name: some

on:   
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPONAME: ${{ github.event.repository.name }}
      GITHUB_USERNAME: ${{ github.actor }}
    steps:
      - run: |
            echo $GITHUB_REPONAME
            echo $GITHUB_USERNAME
