name: some

on:   
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPONAME: ${{ github.event.repository }}
    steps:
      - name: first
        run: | 
            echo toJson($GITHUB_REPONAME)
