name: some

on:   
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPONAME: ${{ toJSON(github.event.repository) }}
    steps:
      - name: first
        run: | 
            echo $GITHUB_REPONAME
